language: python

python: 3.7

env:
  - export GOOGLE_APPLICATION_CREDENTIALS="./serviceAccount.json"

before_install:
  - openssl aes-256-cbc -K $encrypted_2c6bf604352c_key -iv $encrypted_2c6bf604352c_iv -in serviceAccount.json.enc -out serviceAccount.json -d

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install flask_restplus
  - pip install flask
  - pip install werkzeug
  - pip install google-cloud-storage

script:
  - python --version
  - python -m pytest --cov=api tests/