language: python

python: 3.7

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install flask_restplus
  - pip install flask
  - pip install werkzeug
  - pip install google-cloud-storage

script:
  - python --version
  - python -m pytest --cov=api tests/